version: '3.1'

services:
  mysqldb:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Aa123123123123Aa
      MYSQL_USER: user
      MYSQL_PASSWORD: Aa123123123123Aa
    ports:
      - "3306:3306"
    volumes:
      - mysql-db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
  postgresdb:
    image: postgres:14.1-alpine
    container_name: postgresDB
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Aa123123123123Aa
    ports:
      - '5432:5432'

  mssqldb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssqlDB
    restart: always
    hostname: mssqlDB
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Aa123123123123Aa"
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql/data
#  mssql need chmod -R a+rwX access so it can create the basic requirement
  set-permissions:
    image: alpine
    container_name: set-permissions
    command: chmod -R a+rwX /var/opt/mssql/data
    volumes:
      - mssqldata:/var/opt/mssql/data
    depends_on:
      - mssqldb
volumes:
  mysql-db:
  mssqldata:
